[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Development settings
[dev]
  command = "npm run dev:next"
  targetPort = 3000
  port = 8888
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200